In [50]:
"""38:00 / 1:05:23"""
import pandas as pd

df = pd.read_csv("friends.csv")
df

      name        city  marks
0    Harry      Rampur     92
1    Rohan     Kolkata     34
2   Skillf    Bareilly     24
3    Shubh  Antarctica     17
4    Aamit     Kolkata     15
5    Ahmed       Delhi     14
6  Raheman      Mumbai     34

In [51]:
id(df) #to check file location

2696813082448

In [52]:
new_df = df #this is only view of df
id(new_df)

2696813082448

In [53]:
new_df2 = df.copy() #this is a new copy of df
id(new_df2)

2696813239376

In [54]:
df

      name        city  marks
0    Harry      Rampur     92
1    Rohan     Kolkata     34
2   Skillf    Bareilly     24
3    Shubh  Antarctica     17
4    Aamit     Kolkata     15
5    Ahmed       Delhi     14
6  Raheman      Mumbai     34

In [55]:
new_df.loc[0, "name"] = "Abdul" #to update data
df

      name        city  marks
0    Abdul      Rampur     92
1    Rohan     Kolkata     34
2   Skillf    Bareilly     24
3    Shubh  Antarctica     17
4    Aamit     Kolkata     15
5    Ahmed       Delhi     14
6  Raheman      Mumbai     34

In [58]:
df.columns = ["A", "B", "C"] #to change columns name
df

         A           B   C
0    Abdul      Rampur  92
1    Rohan     Kolkata  34
2   Skillf    Bareilly  24
3    Shubh  Antarctica  17
4    Aamit     Kolkata  15
5    Ahmed       Delhi  14
6  Raheman      Mumbai  34

In [64]:
new_df = df.drop(0, axis=0)
new_df

         A           B   C
1    Rohan     Kolkata  34
2   Skillf    Bareilly  24
3    Shubh  Antarctica  17
4    Aamit     Kolkata  15
5    Ahmed       Delhi  14
6  Raheman      Mumbai  34

In [68]:
df.loc[[1,4], ["B", "C"]] #it's only return the value not change

         B   C
1  Kolkata  34
4  Kolkata  15